import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';

const browser = await chromium.launch({ channel: 'chrome', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1080 }, reducedMotion: 'reduce' });
const page = await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.TEST_URL || 'http://127.0.0.1:5173/');
await page.evaluate(()=>document.fonts.ready);
await fs.mkdir('test-results',{recursive:true});
await page.screenshot({path:'test-results/arcade-desktop.png',fullPage:true});
assert.equal(await page.locator('.team-card').count(),2);
assert.equal(await page.locator('h1').textContent(),'Faith Frenzy!');
assert.ok(await page.locator('img.clip-art').evaluateAll(images=>images.every(im=>im.complete&&im.naturalWidth>0)),'all clip art loads');
const artNames=await page.locator('img.clip-art').evaluateAll(images=>[...new Set(images.map(im=>im.src.split('/').pop()))]);
assert.equal(artNames.length,10,'all ten art assets are used');
const categoryNames=await page.locator('.category-art img').evaluateAll(images=>images.map(im=>im.src.split('/').pop()));
assert.equal(new Set(categoryNames).size,6,'every category has its own PNG illustration');
assert.equal(await page.locator('.tile').count(),30);
await page.clock.install();
await page.getByRole('button',{name:'Love of God, 100 points',exact:true}).click();
await page.getByRole('dialog').waitFor();
assert.equal(await page.locator('.timer-toggle > span').textContent(),'10sec');
await page.clock.fastForward(3000);
assert.equal(await page.locator('.timer-toggle > span').textContent(),'7sec');
await page.getByRole('button',{name:'Pause timer',exact:true}).click();
await page.clock.fastForward(3000);
assert.equal(await page.locator('.timer-toggle > span').textContent(),'7sec');
await page.getByRole('button',{name:'Reset',exact:true}).click();
await page.clock.fastForward(10000);
assert.match(await page.locator('.timer-toggle > span').textContent(),/0Time’s up/);
await page.keyboard.press('r');
await page.getByRole('button',{name:'Correct +100',exact:true}).click();
assert.equal(await page.locator('.team-score strong').first().textContent(),'100');
assert.ok(await page.getByRole('button',{name:'Love of God, 100 points, played',exact:true}).isDisabled());
await page.getByRole('button',{name:'Undo',exact:true}).click();
assert.equal(await page.locator('.team-score strong').first().textContent(),'0');
await page.getByRole('button',{name:'Host tools',exact:true}).click();
await page.getByLabel('Team name',{exact:true}).first().fill('Team Mercy');
await page.getByLabel('Score',{exact:true}).first().fill('500');
await page.getByLabel('Score',{exact:true}).nth(1).fill('300');
await page.getByRole('button',{name:'Save changes',exact:true}).click();
await page.reload();
assert.equal(await page.locator('.team-name').first().textContent(),'Team Mercy');
assert.equal(await page.locator('.team-score strong').first().textContent(),'500');
await page.getByRole('button',{name:'Host tools',exact:true}).click();
await page.getByRole('tab',{name:'Edit clues',exact:true}).click();
await page.getByLabel('Clue',{exact:true}).fill('This is a teacher-edited clue.');
await page.getByRole('button',{name:'Save changes',exact:true}).click();
await page.getByRole('button',{name:'Love of God, 100 points',exact:true}).click();
assert.match(await page.locator('.clue-content h2').textContent(),/teacher-edited/);
await page.keyboard.press('Escape');
assert.equal(await page.getByRole('dialog').count(),0);
await page.getByRole('button',{name:'Final challenge',exact:true}).click();
await page.locator('.wager-fields input').first().fill('200');
await page.locator('.wager-fields input').nth(1).fill('100');
await page.getByRole('button',{name:'Lock wagers & show clue',exact:true}).click();
assert.match(await page.locator('.clue-content h2').textContent(),/You go to Sunday Mass/);
await page.getByRole('button',{name:'Reveal final answer',exact:true}).click();
await page.locator('.judge-card').first().getByRole('button',{name:'Correct',exact:true}).click();
await page.locator('.judge-card').nth(1).getByRole('button',{name:'Incorrect',exact:true}).click();
await page.getByRole('button',{name:'Reveal the winners',exact:true}).click();
assert.equal(await page.locator('.results h2').textContent(),'Team Mercy wins!');
assert.equal(await page.locator('.result-card strong').first().textContent(),'700');
assert.equal(await page.locator('.result-card strong').nth(1).textContent(),'200');
await page.getByRole('button',{name:'Back to the board',exact:true}).click();
await page.reload();
await page.getByRole('button',{name:'View results',exact:true}).click();
assert.equal(await page.locator('.results h2').textContent(),'Team Mercy wins!');
await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Host tools',exact:true}).click();
await page.getByRole('button',{name:'New game',exact:true}).click();
await page.getByRole('button',{name:'Yes, reset game',exact:true}).click();
assert.equal(await page.locator('.team-score strong').first().textContent(),'0');
assert.equal(await page.locator('.tile:disabled').count(),0);
for(const width of [390,320]){
 await page.setViewportSize({width,height:844});
 await page.screenshot({path:`test-results/arcade-${width}.png`,fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`board fits ${width}px`);
 await page.getByRole('button',{name:'Love of God, 100 points',exact:true}).click();
 assert.ok(await page.evaluate(()=>document.querySelector('dialog').scrollWidth<=document.querySelector('dialog').clientWidth),`clue fits ${width}px`);
 await page.getByRole('button',{name:'Reveal answer R',exact:false}).click();
 await page.screenshot({path:`test-results/clue-${width}.png`,fullPage:true});
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Host tools',exact:true}).click();
 assert.ok(await page.evaluate(()=>document.querySelector('dialog').scrollWidth<=document.querySelector('dialog').clientWidth),`host fits ${width}px`);
 await page.keyboard.press('Escape');
}
await page.setViewportSize({width:1366,height:768});
await page.screenshot({path:'test-results/arcade-projector.png',fullPage:true});
assert.ok(await page.locator('.final-button').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight),'final controls fit a 768px projector');
for(const [width,height] of [[1440,900],[1366,768],[940,650],[768,650],[390,844],[320,640]]){
 await page.setViewportSize({width,height});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1),`whole game fits ${width}x${height}`);
 assert.ok(await page.locator('.final-button').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight),`final button visible at ${width}x${height}`);
 await page.screenshot({path:`test-results/fit-${width}x${height}.png`,fullPage:true});
}
assert.deepEqual(errors,[]);
const motionPage=await browser.newPage({viewport:{width:1440,height:1080},reducedMotion:'no-preference'});
await motionPage.goto(process.env.TEST_URL || 'http://127.0.0.1:5173/');
await motionPage.getByRole('button',{name:'Love of God, 100 points',exact:true}).click();
assert.equal(await motionPage.locator('.clue-modal').evaluate(el=>getComputedStyle(el).animationName),'clue-flip-in');
await motionPage.getByRole('button',{name:'Reveal answer R',exact:false}).click();
await motionPage.getByRole('button',{name:'Correct +100',exact:true}).click();
await motionPage.locator('.celebration').waitFor();
assert.equal(await motionPage.locator('.pixel-confetti').count(),28);
await motionPage.getByRole('button',{name:'Gather & Begin, 100 points',exact:true}).click();
await motionPage.getByRole('button',{name:'Close dialog',exact:true}).click();
await motionPage.locator('.celebration').waitFor({state:'detached'});
await motionPage.close();
console.log('Browser checks passed: ten PNG assets and six distinct category illustrations, arcade motion and nonblocking celebration, automatic 10s timer, pause/reset/expiry, scoring/undo, editing, persistence, final wagers/results, reset, and 320px/390px layouts.');
await browser.close();
